[package]
name = "common-arrow"
version = "0.1.0"
edition = "2021"

[lib]
name = "common_arrow"

[dependencies]
arrow = {version = "0.17", package = "arrow2", features = ["io_print"]}
#arrow-format = { version = "0.8.0", features = ["flight-data", "flight-service", "ipc"] }